=== AlessioBorriero/OpenForBC-Benchmark/jsonschema/benchmark.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/openforbc.benchmark.schema.json",

  "title": "Open-ForBC benchmark schema",
  "description": "A benchmark JSON definition schema",

  "$defs": {
    "command": {
      "oneOf": [ { "type": "string" }, {
        "type": "object",
        "properties": {
          "path": { "type": "string" },
          "env": {
            "type": "object",
            "additionalProperties": { "type": "string" }
          },
          "workdir": { "type": "string" }
        },
        "additionalProperties": false,
        "required": [ "path" ]
      } ]
    },
    "commands": {
      "oneOf": [
        { "$ref": "#/$defs/command" },
        { "type": "array", "items": { "$ref": "#/$defs/command" } }
      ]
    },
    "match": {
      "type": "object",
      "properties": {
        "regex": { "type": "string" },
        "file": { "type": "string" }
      },
      "additionalProperties": false,
      "required": [ "regex" ]
    }
  },

  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the benchmark",
      "type": "string"
    },
    "description": {
      "description": "A brief description of the benchmark",
      "type": "string"
    },
    "setup_command": {
      "description": "Command to be executed in order to setup the benchmark",
      "$ref": "#/$defs/commands"
    },
    "run_command": {
      "description": "Command to be executed in order to run the benchmark",
      "$ref": "#/$defs/commands"
    },
    "cleanup_command": {
      "description": "Command to be executed in order to do cleanup after running the benchmark",
      "$ref": "#/$defs/commands"
    },
    "stats": {
      "description": "Command to be executed in order to fetch stats or a set of stats",
      "oneOf": [
        { "type": "string" },
        { "type": "object", "additionalProperties": { "$ref": "#/$defs/match" } }
      ]
    },
    "virtualenv": {
      "description": "Whether to create and activate a virtualenv for this benchmark commands",
      "type": "boolean"
    }
  },
  "additionalProperties": false,
  "required": [ "name", "description", "run_command", "stats" ]
}

=== AlessioBorriero/OpenForBC-Benchmark/benchmarks/matmul_benchmark/benchmark.json
{
    "name": "Matrix Multiplication Benchmark using Tensorflow",
    "description": "Some test of matrices operations",
    "setup_command": "./setup.sh",
    "run_command": "./matmul_benchmark.py",
    "stats": {
        "matmul_time_ns":{
            "regex": "Matrix multiplcation time: (\\d+)s"
        }
    },
    "virtualenv": true   
}

=== AlessioBorriero/OpenForBC-Benchmark/benchmarks/MNIST_FCNeuralNetwork/benchmark.json
{
    "name": "Fully Connected Neural Network training and inference over MNIST dataset ",
    "description": "Trainign and inference with MNIST dataset",
    "setup_command": "./setup.sh",
    "run_command": "MNIST_FCNeuralNetwork_benchmark.py",
    "stats": {
        "matmul_time_ns":{
            "regex": "Sample time processing during training: (\\d+) sample/seconds"
        },
        "matmul_time_ns":{
            "regex": "Sample time processing during inference in-sample: (\\d+) sample/seconds"
        },
        "matmul_time_ns":{
            "regex": "Sample time processing during inference out-of-sample: (\\d+) sample/seconds"
        }
    },
    "virtualenv": true   
}

=== AlessioBorriero/OpenForBC-Benchmark/benchmarks/blender_benchmark/benchmark.json
{
  "name": "Blender Benchmark",
  "description": "Runs one/many blender scene(s) and outputs stats",
  "setup_command": [
    "./setup.sh",
    "./setup.py",
    "chmod +x bin/benchmark-launcher-cli"
  ],
  "run_command": "bin/benchmark-launcher-cli benchmark --json",
  "stats": "true",
  "virtualenv": true
}
